version: "3.8"

services:
  # MYSQL
  db:
    image: mysql:8.4
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql:/etc/mysql/certs
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=form_data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_PASSWORD=${PHPMYADMIN_PASSWORD}
    links:
      - db:db

  # APACHE
  apache:
    image: lavoweb/php-8.3
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db:database

  # NEXTJS
  nextjs:
    build: ./site
    ports:
      - "3000:3000"
    command: npm start